# Introduction

## Basic Information
`r Spp` (\emph{`r spp.sci`}) is a right-eyed flounder in the family Pleuronectidae ranging from the western Gulf of Alaska to the Coronado Islands, northern Baja California [@kramer_guide_1995; @love_milton_resource_2005] with a preference for soft substrates at depths ranging from 0-550 m [@love_milton_resource_2005]. Common names include brill, California sole, Jordan's flounder, cape sole, round nose sole, English sole, soglia, petorau, nameta, and tsubame garei [@smith_report_1937; @gates_designated_1974; @love_milton_probably_1996; @eschmeyer_field_1983]. In northern and central California `r spp` are dominant on the middle and outer continental shelf. \gls{pacfin} fishery logbook data show that adults are caught in depths from 18 to 1,280 m off the U.S. West Coast with a majority of the catches of `r spp` being taken between 70-220 m during March through October, and between 290-440 m during November through February.

There is little information regarding the stock structure of `r spp` off the U.S. West Coast. No genetic research has been undertaken for `r spp` and there is no other published research indicating separate stocks of `r spp` within U.S. waters. Tagging studies show adult `r spp` can move up to 350 - 390 miles, having the ability to be highly migratory with the possibility for homing ability [@alverson_results_1957]. Juveniles show little coastwide or bathymetric movement while studies suggest that adults generally move inshore and northward onto the continental shelf during the spring and summer to feeding grounds and offshore and southward during the fall and winter to deep water spawning grounds [@horton_species_1989; @love_milton_probably_1996]. Adult `r spp` can tolerate a wide range of bottom temperatures [@perry_environmental_1994].

Tagging studies indicate some mixing of adults between different spawning groups. DiDonato and Pasquale [-@didonato_migration_1970] reported that five fish tagged on the Willapa Deep grounds during the spawning season were recaptured during subsequent spawning seasons at other deepwater spawning grounds, as far south as Eureka (northern California) and the Umpqua River (southern Oregon). However, Pedersen [-@pedersen_movements_1975] reported that most of the fish (97%) recaptured from spawning grounds in winter were originally caught and tagged on those same grounds.

Mixing of fish from multiple deep water spawning grounds likely occurs during the spring and summer when `r spp` are feeding on the continental shelf. Fish that were captured, tagged, and released off the northwest Coast of Washington during May and September were subsequently recaptured during winter from spawning grounds off Vancouver Island (British Columbia, 1 fish), Heceta Bank (central Oregon, 2 fish), Eureka (northern California, 2 fish), and Halfmoon Bay (central California, 2 fish) (Pederson, 1975). Fish tagged south of Fort Bragg (central California) during July 1964 were later recaptured off Oregon (11 fish), Washington (6 fish), and Swiftsure Bank (southwestern tip of Vancouver Island, 1 fish) (D. Thomas, California Department of Fish and Game, Menlo Park, CA, cited by Sampson and Lee [-@sampson_assessment_1999]).

The highest densities of spawning adults off of British Columbia, as well as of eggs, larvae and juveniles, are found in the waters around Vancouver Island. Adults may utilize nearshore areas as summer feeding grounds and non-migrating adults may stay there during winter [@starr_petrale_2004].

Past assessments completed by Demory [-@demory_progress_1984], Turnock et al. [-@turnock_status_1993], and Sampson and Lee [-@sampson_assessment_1999] considered `r spp` in the Columbia and U.S.-Vancouver \gls{inpfc} areas a single stock. Sampson and Lee (1999) assumed that `r spp` in the Eureka and Monterey \gls{inpfc} areas represented two additional distinct socks. The 2005 `r spp` assessment assumed two stocks, northern (U.S.-Vancouver and Columbia \gls{inpfc} areas) and southern (Eureka, Monterey and Conception \gls{inpfc} areas), to maintain continuity with previous assessments. Three stocks (West Coast Vancouver Island, Queen Charlotte Sound, and Heceta Strait) are considered for `r spp` in the waters off British Columbia, Canada [@starr_petrale_2004]. The 2009, 2011, 2013, 2015 and 2019 assessments in the U.S. integrate the previously separate north-south assessments to provide a coastwide status evaluation. The decision to conduct a single-area assessment is based on strong evidence of a mixed stock from tagging studies, a lack of genetic studies on stock structure, a lack of evidence for differences in growth between the areas, and from examination of the fishery size-at-age data, as well as confounding differences in data collection between Washington, Oregon, and California.

This  assessment provides a coastwide status evaluation for `r spp` using data through 2022. The U.S.-Canadian border is the northern boundary for the assessed stock, although the basis for this choice is due to political and current management needs rather than the population dynamics (Figure \ref{fig:map}). Given the lack of clear information regarding the status of distinct biological populations, this assessment treats the U.S. `r Spp` resource from the Mexican border to the Canadian border as a single coastwide stock. Fishing fleets are separated geographically to account for spatial patterns in catch given the coastwide assessment area.  

## Life History
`r Spp` spawn during the winter at several discrete deepwater sites (270-460 m) off the U.S. West Coast, from November to April, with peak spawning taking place from December to February [@harry_analysis_1956; @best_petrale_1960; @gregory_validity_1976; @castillo_g.c._environmental_1993; @reilly_recreational_1994; @castillo_latitudinal_1995; @love_milton_probably_1996]. Females spawn once each year and fecundity varies with fish size, with one large female laying as many as 1.5 million eggs [@porter_notes_1964]. `r Spp` eggs are planktonic, ranging in size from 1.2 to 1.3 mm, and are found in deep water habitats at water temperatures of 4-10 degrees C and salinities of 25-30 ppt [@best_petrale_1960; @ketchen_population_1966; @alderdice_effects_1971; @gregory_validity_1976]. The duration of the egg stage can range from approximately 6 to 14 days [@alderdice_effects_1971; @love_milton_probably_1996]. The most favorable conditions for egg incubation and larval growth are 6-7 degrees C and 27.5-29.5 ppt [@ketchen_population_1966; @alderdice_effects_1971]. 

`r Spp` spawn during the winter at several discrete deepwater sites (270-460 m) off the U.S. West Coast, from November to April, with peak spawning taking place from December to February [@harry_time_1959; @best_petrale_1960; @gregory_validity_1976; @castillo_g.c._environmental_1993; @reilly_recreational_1994; @love_milton_probably_1996]. Females spawn once each year and fecundity varies with fish size, with one large female laying as many as 1.5 million eggs [@porter_notes_1964]. `r Spp` eggs are planktonic, ranging in size from 1.2 to 1.3 mm, and are found in deep water habitats at water temperatures of 4-10 degrees C and salinities of 25-30 ppt [@best_petrale_1960; @ketchen_population_1966;  @alderdice_effects_1971; @gregory_validity_1976]. The duration of the egg stage can range from approximately 6 to 14 days [@alderdice_effects_1971; @love_milton_probably_1996]. The most favorable conditions for egg incubation and larval growth are 6-7 degrees C and 27.5-29.5 ppt [@ketchen_population_1966; @alderdice_effects_1971; @castillo_latitudinal_1995].

Adult `r spp` achieve a maximum size of around 50 cm and 63 cm for males and females, respectively [@best_e.a._movements_1963; @pedersen_movements_1975]. The maximum length reported for `r spp` is 70 cm [@eschmeyer_field_1983; @love_milton_resource_2005] while the maximum observed break-and-burn age is 31 years [@haltuch_status_2013].

## Ecosystem Considerations
`r Spp` juveniles are carnivorous, foraging on annelid worms, clams, brittle star, mysids, sculpin, amphipods, and other juvenile flatfish [@casilla_essential_1998; @pearsall_diet_2007]. Predators on juvenile `r spp` include adult `r spp` as well as other larger fish [@casilla_essential_1998] while adults are preyed upon by marine mammals, sharks, and larger fishes [@trumble_abundance_1995; @love_milton_probably_1996; @casilla_essential_1998].

One of the ambushing flatfishes, adult `r spp` have diverse diets that become more piscivorous at larger sizes [@allen_ecology_2006]. Adult `r spp` are found on sandy and sand-mud bottoms [@eschmeyer_field_1983] foraging for a variety of invertebrates including, crab, octopi, squid, euphausiids, and shrimp, as well as anchovies. hake, herring, sand lance, and other smaller rockfish and flatfish [@kravitz_food_1977; @birtwell_fish_1984; @reilly_recreational_1994; @love_milton_probably_1996; @pearsall_diet_2007]. In Canadian waters evidence suggests that `r spp` tend to prefer herring [@pearsall_diet_2007]. On the continental shelf `r spp` generally co-occur with English sole, rex sole, Pacific sanddab, and rock sole [@kravitz_food_1977].

There are several aspects of the California current ecosystem that may impact `r spp` population dynamics. Castillo [-@castillo_g.c._fluctuations_1992] and Castillo et al. [-@castillo_latitudinal_1995] suggest that density-independent survival of early life stages is low and show that offshore Ekman transportation of eggs and larvae may be an important source of variation in year-class strength in the Columbia \gls{inpfc} area. The effects of the Pacific Decadal Oscillation (PDO) on California current temperature and productivity [@mantua_pacific_1997] may also contribute to non-stationary recruitment dynamics for `r spp`. The prevalence of a strong late 1990s year-class for many West Coast groundfish species suggests that environmentally driven recruitment variation may be correlated among species with relatively diverse life history strategies. 

Over the past several years, progress has been made in understanding how large-scale climate forcing drives regional changes and impacts density-independent survival during `r spp` early life stages. Haltuch et al. [-@haltuch_oceanographic_2020] examined the relationship between `r spp` recruitment and oceanographic drivers based on model output from a Regional Ocean Modeling System (ROMS) model for the California Current Ecosystem (Neveu et al. 2016). The results suggested that ROMS output might be useful as the basis for an environmental index of recruitment for `r spp`, to allow for better model precision and near-term forecasting. However, the ROMS model used by Haltuch et al. [-@haltuch_oceanographic_2020] was consistent in structure and inputs for 1980-2010. From 2011 forward, ROMS outputs exhibit distinct discontinuities with 1980-2010 period, showing changes in scale and trend across the 2010/2011 boundary. 

Due to discontinuity in ROMS models between periods before and after 2011, the index developed by Haltuch et al. [-@haltuch_oceanographic_2020] could not be used for this stock assessment. However, an alternative oceanographic model products by Copernicus Marine Environment Monitoring Service (CMEMS) (https://marine.copernicus.eu/) and Mercator Ocean International (MOI) (https://www.mercator-ocean.eu/) were investigated to test if this modelling framework could be used to produce an environmental index of `r spp` recruitment. This new effort is ongoing, and has not yet been published or reviewed by the SSC. In this assessment, we explore the impact of the current CMEMS-based environmental index of `r spp` recruitment via sensitivity analysis.

Appendix A of this report describes the most recent, preliminary efforts in developing a new environmental index of `r spp` recruitment based on CMEMS products. Appendix A also discusses potential reasons for why the ROMS time series changed over the 2010/2011 boundary and how those changes might impact the ROMS-based recruitment index from Haltuch et al. [-@haltuch_oceanographic_2020].

## Historical and Current Fishery Information
`r Spp` have been caught in the flatfish fishery off the U.S. West Coast since the late 19th century. The fishery first developed off of California where, prior to 1876, fishing in San Francisco Bay was by hand or set lines and beach seining [@scofield_trawling_1948]. By 1880 two San Francisco based trawler companies were running a total of six boats, extending the fishing grounds beyond the Golden Gate Bridge northward to Point Reyes [@scofield_trawling_1948]. Steam trawlers entered the fishery during 1888 and 1889, and four steam tugs based out of San Francisco were sufficient to flood market with flatfish [@scofield_trawling_1948]. By 1915 San Francisco and Santa Cruz trawlers were operating at depths of about 45-100 m with catches averaging 10,000 lbs per tow or 3,000 lbs per hour [@scofield_trawling_1948]. Flatfish comprised approximately 90% of the catch with 20-25% being discarded as unmarketable [@scofield_trawling_1948]. During 1915 laws were enacted that prohibited dragging in California waters and making it illegal to possess a trawl net from Santa Barbara County southward [@scofield_trawling_1948]. By 1934 twenty 56-72 foot diesel engine trawlers operated out of San Francisco fishing between about 55 and 185 m [@scofield_trawling_1948]. From 1944-1947 the number of California trawlers fluctuated between 16 and 46 boats [@scofield_trawling_1948]. Although the flatfish fishery in California was well developed by the 1950s and 1960s, catch statistics were not reported until 1970 [@heimann_pacific_1970]. In this early California report `r spp` landings during 1916 to 1930 were not separated from the total flatfish landings. 

The earliest trawl fishing off Oregon began during 1884-1885, and the fishery was solidly established by 1937. Initially trawlers stayed close to the fishing grounds adjacent to Newport and Astoria, operating at about 35-90 m between Stonewall Bank and Depoe Bay. Fishing operations gradually extended into deep water. For example, Newport-based trawlers were commonly fishing at about 185 m in 1949, at about 185-365 m by 1952, and at about 550 m by 1953.

Alverson and Chatwin [-@alverson_results_1957] describe the history of the `r spp` fishery off of Washington and British Columbia with fishing grounds ranging from Cape Flattery to Destruction Island. `r Spp` catches off of Washington were small until the late 1930s with the fishery extending to about 365 m following the development of deepwater rockfish fisheries during the 1950s.

The `r spp` catches further increased rapidly during World War II in response to increased demands (Harry and Morgan, 1961). Also, during the "vitamin A rush" in the late 1930s and 1940s it was found that `r spp` has high levels, which contributed to increased catches of this species as well. By the 1950s, the fishery was well developed with the stock showing declines in biomass and catches (Figures \ref{fig:catch-figures-r4ss} and \ref{fig:smry-bio-historical}). Also in the 1950s, winter spawning grounds at deeper depths with dense concentrations of `r spp` were discovered, and catches increased accordingly (e.g., @alverson_results_1957; @ketchen_population_1966). 

Both historical and current `r spp` fisheries have primarily relied upon trawl fleets, and `r Spp` have been harvested almost exclusively by bottom trawls in the U.S. West Coast groundfish fishery. The rate of decline in spawning biomass accelerated through the 1970s reaching minimums estimated to be generally around or below 10% of the unexploited levels during the 1980s through the early 2000s. Recent annual catches between 1981-2022 range between 803 and 3060 mt per year (Table \ref{tab:catch-table}). 

`r Spp` are a desirable market species and discarding has historically been low (less than 5%), with most of the discarding due to small sizes. 

Fishery removals are divided between two fleets: 1) North, and 2) South. Landings for the North fleet are defined as fish landed in Washington and Oregon ports. Landings for the South fleet are defined as fish landed in California ports.

## Summary of Management History and Performance
Beginning in 1983 the Pacific Fishery Management Council (PFMC) established coastwide annual catch limits (ACLs) for the annual harvests of `r spp` in the waters off the U.S. West Coast. The first assessment of West Coast `r spp` occurred in 1984 [@demory_progress_1984]. Based on the 1999 assessment a coastwide ACL of 2,762 mt was specified and remained unchanged between 2001 and 2006.

The 2005 assessment of `r spp` stock assessment split the stock into two areas, the northern area that included U.S.-Vancouver and Columbia \gls{inpfc} areas and the southern area that included the Eureka, Monterey and Conception \gls{inpfc} areas [@lai_stock_2005]. While `r spp` stock structure is not well understood, \gls{cpue} and geographical differences between states were used to support the use of two separate assessment areas. In 2005 `r spp` were estimated to be at 34 and 29% of unfished spawning stock biomass in the northern and southern areas, respectively. In spite of different models and data, the biomass trends were qualitatively similar in both areas, providing support for a coastwide stock. This assessment estimated that `r spp` had historically been below the Pacific Council's minimum stock size threshold of 25% of unfished biomass from the mid-1970s until just prior to the completion of the assessment, with estimated harvest rates in excess of the target fishing mortality rate implemented for `r spp` at that time (F40%). However, the 2005 stock assessment determined that the stock was in the precautionary zone and was not overfished (i.e., the spawning stock biomass was not below 25% of the unfished spawning stock biomass). Based on the 2005 stock assessment results, ACLs were set at 3,025 mt and 2,919 mt for 2007 and 2008, respectively, with an ACT of 2,499 mt for both years. 

In comparison to the 1999 assessment of `r spp`, the 2005 assessment represented a significant change in the perception of `r spp` stock status. The stock assessment conducted in 1999 (Washington-Oregon only) estimated the spawning stock biomass in 1998 at 39% of unfished stock biomass. Although the estimates of 1998 spawning-stock biomass were little changed between the 1999 and 2005 (Northern area) assessments, the estimated depletion in the 2005 assessment was much lower. The change in status between the 1999 and 2005 analyses was due to the introduction of a reconstructed catch history in 2005, which spanned the entire period of removals. The 1999 stock assessment used a catch history that started in 1977, after the bulk of the removals from the fishery had already taken place. Thus the 1999 stock assessment produced a more optimistic view of the petrale stock's level of depletion. 

The 2009 coastwide stock assessment estimated that the `r spp` stock had declined from its 2005 high to 11.6% of the unfished spawning stock biomass [@haltuch_status_2009]. The stock's estimated decline in status between the 2005 and 2009 assessments was driven primarily by a significant decline in the trawl-survey index over that period. The 2011 assessment concluded that the stock status continued to be below the target of 25% of unfished biomass. The `r spp` was declared overfished based on newly adopted management targets (target spawning output for flatfish stocks defined as 25% and overfished threshold of 12.5% of unfished spawning output) resulting in a rebuilding plan and catch restrictions for `r spp`. The stock was declared rebuilt based on the results of the 2015 update stock assessment which estimated the coastwide biomass at 30.7% of unfished spawning stock output [@stawitz_stock_2015]. 

## Fisheries off Canada and Alaska
The Canadian fishery developed rapidly during the late 1940s to mid-1950s following the discovery of `r spp` spawning aggregations off the West Coast of Vancouver Island [@anon_fish_2001]. Annual landings of `r spp` in British Columbia peaked at 4,800 mt in 1948 but declined significantly after the mid-1960s [@anon_fish_2001]. By the 1970s, analysis conducted by Pederson [-@pedersen_movements_1975] suggested that `r spp` abundance was low and abundance remained low into the 1990s. In the early 1990s vessel trip quotas were established to try to halt the decline in `r spp` abundance [@anon_fish_2001]. Winter quarter landings of `r spp` were limited to 44,000 lb per trip during 1985-91; to 10,000 lb per trip during 1991-95; and to 2,000 lb per trip in 1996. Biological data collected during 1980-1996 showed a prolonged decline in the proportion of young fish entering the population [@anon_fish_2001]. Therefore, no directed fishing for `r spp` has been permitted in Canada since 1996 due to a continuing decline in long term abundance [@fargo_j.j._flatfish_1997; @anon_fish_2001]. As of 2005 `r spp` off of British Columbia were treated as three "stocks" and were still considered to be at low levels. The recent assessments for the Canadian stocks have been based on catch histories and limited biological data. A new stock assessment is currently being conducted by \ref{dfo} for `r spp` in Canadian waters although results are not expected to be available until months after the completion of this one (pers. comm. M. Mazur, \ref{dfo}).

In Alaska `r spp` are not targeted in the Bering Sea/Aleutian Island fisheries and are managed as a minor species in the "Other Flatfish" stock complex.
