### \acrlong{s-tri}

#### Survey Description

The \gls{s-tri} was first conducted by the \gls{afsc} in 1977, and the survey continued until 2004 [@weinberg_2001_2002]. 

Its basic design was a series of equally-spaced east-to-west transects across the continential shelf from which searches for tows in a specific depth range were initiated. The survey design changed slightly over time. In general, all of the surveys were conducted in the mid summer through early fall. The 1977 survey was conducted from early July through late September. The surveys from 1980 through 1989 were conducted from mid-July to late September. The 1992 survey was conducted from mid-July through early October. The 1995 survey was conducted from early June through late August. The 1998 survey was conducted from early June through early August. Finally, the 2001 and 2004 surveys were conducted from May to July.

Haul depths ranged from 91-457 m during the 1977 survey with no hauls shallower than 91 m. Due to haul performance issues and truncated sampling with respect to depth, the data from 1977 were omitted from this analysis. The surveys in 1980, 1983, and 1986 covered the U.S. West Coast south to 36.8\textdegree N latitude and a depth range of 55-366 m. The surveys in 1989 and 1992 covered the same depth range but extended the southern range to 34.5\textdegree N (near Point Conception).
From 1995 through 2004, the surveys covered the depth range 55-500 m and surveyed south to 34.5\textdegree N. The distribution of `r spp` in the survey relative to these limits is shown in Figure \ref{fig:depth-vs-lat-tri}. 

In 2004, the final year of the \gls{s-tri} series, the \gls{nwfsc} \gls{fram} conducted the survey following similar protocols to earlier years. Although the protocol was similar, subtle differences in how it had been implemented prior to 2004 may have contributed to a large difference in estimated biomass between 2001 and 2004, where few of the West Coast groundfish stock assessments have been able to match the observed increase in 2004 relative to the previous years.

#### Index of Abundance

Geostatistical models of biomass density were fit to survey data using \gls{tmb} [@kristensen_tmb:_2016] via the R package \gls{sdmtmb} [@Anderson:2022:SRP]. These models can account for latent spatial factors with a constant spatial Gaussian random field and spatiotemporal deviations to evolve as a random walk Guassian random field [@thorson_geostatistical_2015]. Tweedie, delta-binomial, delta-gamma, and mixture distributions, which allow for extreme catch events, were investigated. Results are only shown for the distribution that led to the best model diagnostics, e.g., similar distributions of theoretical normal quantiles and model quantiles, high precision, lack of extreme predictions that are incompatible with the life history, and low \gls{aic}. Estimates of biomass from this best model were predicted using a grid based on available survey locations. Code to reproduce the analysis is available at
https://github.com/pfmc-assessments/indexwc.

In this assessment, a single  \gls{s-tri} index (1980--2004) was developed. Sensitivity analysis was conducted to evaluate impact of using a single abundance index versus two indices with a split in 1995 (to account for change in spatial coverage and survey timing), as well as using a single index but estimating a separate catchability parameter for the period from 1995 forward, and others. All sensitivity runs resulted in virtually identical results, and the most parsimonious approach (a single survey index) was retained for the base model (Section \@ref(sensitivity-analyses)).   

The data were truncated to latitudes north of 37\textdegree N latitude and to depths less than 366 m prior to modeling, to only include survey area consistent in spatial coverage among years. The prediction grid was also truncated to only include available survey locations in depths between 55–366 m to limit extrapolating beyond the modeled area and edge effects. 

The model used a delta model with a lognormal distribution for the catch-rate component. A logit-link was used for encounter probability and a log-link for positive catch rates. The response variable was catch (mt) with an offset of area (km$^2$) to account for differences in effort. Fixed effects were estimated for each year. No other covariates were modelled. Vessel-year effects, which have traditionally been included in index standardization for this survey, were not included as the estimated variance for the random effect was close to zero. Vessel-year effects were more prominent when models did not include spatial effects and were included for each unique combination of vessel and year in the data to account for the random selection of commercial vessels used during sampling [@helser_generalized_2004; @thorson_accounting_2014].

Spatial and spatiotemporal variation was included in the encounter probability and the positive catch rate model.
Spatial variation was approximated using 500 knots, where more knots led to non-estimable standard errors because the positive encounters are too sparse to support the dense spatiotemporal structure.

The estimated distribution of `r spp` density for 2004 is shown in Figure \ref{fig:survey-density}.

#### Length Compositions

Length bins from 12 to 62 cm in 2 cm increments were used to summarize the length frequency of the survey catches in each year. Table \ref{tab:sample-size-length-tri} shows the number of lengths taken by the survey. 

Prior to 1989, only limited length samples were collected and those samples were limited to the Northern area of the survey; therefore, length samples from years prior to 1989 are not used in the assessment. Less than a half percent of all length samples were collected in depths deeper than 350 m. Therefore, truncation of data to depths less than 350 m (for development of a single abundance index) did not impact length composition samples. 

Length compositions were separated into males and females. These length compositions were expanded to account for subsampling tows, with further expansion based upon the stratification by depth and latitude. The stratifications for length data expansions are provided in Table \ref{tab:strata-tri}.

The input sample sizes for length composition data for all fishery-independent surveys were calculated based on Stewart and Hamel [-@stewart_bootstrapping_2014] as $\text{Input N}_{y} = 3.09*N_{tow}$ where the 3.09 value was estimated for a group of 8 flatfish species including `r spp`.

There are no `r spp` age data from the \gls{s-tri}, and the \gls{s-tri} sampling manual does not mention collecting age structures from flatfish species.

Processing of length and age data from both surveys was conducted using the {nwfscSurvey} package in R [@wetzel_nwfscsurvey_2023].
