## Biological Data

### Natural Mortality

The instantaneous rate of natural mortality for a wild fish population is notoriously difficult to estimate. One accepted method is to examine the age distribution of an unexploited or lightly exploited stock. This method cannot readily be applied to `r spp` given the long history of exploitation off the U.S. West Coast. Ketchen and Forrester [-@ketchen_population_1966] estimated that the natural mortality coefficients were 0.18-0.26 yr^-1^ for males and 0.19-0.21 yr^-1^ for females based on a catch curve analysis of 1943--1945 Washington trawl data from Swiftsure Bank, off the southwest corner of Vancouver Island. However, `r spp` catches were relatively high during mid-1940s through the 1950s. Starr and Fargo [-@starr_petrale_2004] estimated the instantaneous rate of natural mortality ($M$) using Hoenig's method [@hoenig_empirical_1983] estimating $M$ values of 0.22 and 0.15 yr^-1^ were estimated given maximum ages of 20 and 30 years, respectively.   

An archived set of commercial samples, collected from Northern California between the late 1950s and early 1980s, recently found that multiple samples were aged between 20--31 years old, suggesting a similar range of $M$ values for U.S. West Coast `r spp`. U.S. stock assessments prior to 2009 and current British Columbia stock assessments assumed a value of $M$ = 0.2 yr^-1^ for both sexes. The 2013 stock assessment used a meta-analysis value produced the following normal prior distributions for females (mean = 0.151, sd = 0.16) and males (0.206, sd = 0.218) based on Hamel [-@hamel_method_2015] with maximum age for females and males of 32 and 29 years, respectively.

Hamel [-@hamel_method_2015], recently updated by Hamel and Cope [-@hamel_development_2022], represents the current method for developing a prior on natural mortality for West Coast groundfish stock assessments. This method combines meta-analytic approaches relating the natural mortality rate to other life-history parameters to develop a general prior on $M$ for many fish species. The updated approach modifies work done by Then et al.[-@then_evaluating_2015] who estimated $M$ and recommended $M$ estimates based on maximum age alone. Hamel [-@hamel_development_2022] re-evaluated the data used by Then et al. [-@then_evaluating_2015] by fitting the one-parameter $A_{\text{max}}$, model under a log-log transformation and also reduced the variance around the estimate. The resulting equation for the point estimate (i.e., the median, in real space) for $M$, is:

\begin{centering}

$M=\frac{5.4}{A_{\text{max}}}$

\end{centering}

where  $A_{\text{max}}$ is the maximum age of the focal species. The above is also the median of the prior. The prior is defined as a lognormal distribution with mean (in log space) $ln(5.4/A_{\text{max}})$ and SE = 0.31. 

Maximum age was assumed to be 32 and 29 years for females and males, respectively, consustent with several previous assessments. Using the Hamel and Cope [-@hamel_development_2022] approach above, the median of the prior for females in regular space is `r round(5.4/32, 3)` and for males is `r round(5.4/29, 3)`. 

### Maturation and Fecundity{#mat_fecund}

A new maturity ogive was developed for this assessment (pers. comm. M. Head, NWFSC) based on an analysis of 553 ovary samples collected from 2015 to 2021 by port samplers in Washington and Oregon as well as on board the \gls{s-wcgbt} (Figures \ref{fig:mod-est-len-age2} and \ref{fig:maturity}). Very little difference in biological and functional maturity was observed and there was evidence of only a minimal amount of skip spawning. The estimated length at 50\% maturity was 35.45, which was similar to the 33.1 cm used in the previous assessment which was based on samples from a narrower geographic range [@hannah_length_2002].

A fecundity relationship published in 2019 [@lefebvre_reproductive_2019] was used as a sensitivity analysis in the previous assessment and has been adopted for the base model in this one. The relationship shows a slightly faster increase in the number of eggs per unit length than when fecundity was assumed proportional to body weight. The addition of this fecundity relationship means that spawning output is reported in trillions of eggs rather than metric tons of spawning biomass. 

<!-- TODO: add figure (perhaps copied from 2019 assessment) and note the parameter values. -->

### Sex Ratio

The fraction of the smallest and youngest `r spp` observed in the \gls{s-wcgbt} (less than 35 cm or younger than age 5) identified as female is less than 50%. No study on what determines phenotypic sex for `r spp` has been conducted, but environmental sex determination (ESD) has been established for many other flatfish, where environmental factors can influence phenotypic sex in the female genotype, resulting in male-skewed sex ratios [@luckenbach_sex_2009; @honeycutt_warmer_2019]. The sex ratio of larger and older fish is skewed toward females presumably due to lower natural mortality.

As a part of this assessment, we explored multiple model formulations with age-0 fraction female estimated internally. However, in many of those formulations, age-0 fraction female was estimated above 50% due to confounding with sex-specific selectivity. The reasonable estimate of age-0 fraction female was achieved only when a single selectivity curve was assumed for the females and males in the \gls{s-wcgbt}, which deteriorated fit to length composition data. Furthermore, the length and age bins which are skewed male in the \gls{s-wcgbt} contain so few fish relative to larger sizes, that the influence of a sex ratio estimate different from 50% was minimal. The value of estimated age-0 fraction female in that model run was 0.48, and it was assumed reasonable to continue to use a 50% sex ratio at birth between females and males, consistent with previous assessments.   

### Length-Weight Relationship

`r load("../data/weight-length_pars.rda")`
The weight-length relationship for `r spp` was estimated outside of the 
assessment model by fitting biological data to the standard power function, 
$W = aL^b$ using the R function `PacFIN.Utilities::getWLpars()` 
(where $W$ is weight in kilograms and $L$ is length in centimeters). 
The function estimates the relationship on a log-log scale and then uses the 
estimated standard deviation of the observed weights around the expected value 
to calculate the median weight at each length from the resulting lognormal 
distribution.

The parameters were estimated using data from the \gls{s-wcgbt}, where 21,704 
fish collected between 2003 and 2022 had both weight and length available 
of which 57.6\% were female, 42.3\% were male, and 0.1\% were unsexed. 
The resulting relationships were
`r sprintf("$W=%1.9f * L^{%1.3f}$", fa, fb)` for females and
`r sprintf("$W=%1.9f * L^{%1.3f}$", ma, mb)` for males. 
These relationships are very similar to those used for the previous assessment 
[@wetzel_status_2019].

### Growth (Length-at-Age)

The length-at-age was estimated for male and female `r spp` via 5 von Bertalanffy parameters, with independent parameters for length at age 17 (L_at_Amax) for females and males, independent $k$ parameters, and a shared parameter for length at age 1 for both females and males. Variability in length at age was estimated via 2 parameters for each sex controlling the standard deviation of length-at-age as a piecewise linear function of length with breaks points at lengths associated with the two reference ages: 1 and 17. This differs from the 2019 assessment which parameterized variability in length-at-age as a CV rather than standard deviation, and used age 2 as the first reference age. The changes resulted in smoother changes in the distributions of length-at-age and avoided a bulge in the variability at young ages that was present in the 2019 model.

### Ageing Precision and Bias

Historically, `r spp` otoliths have been read by multiple ageing labs using surface and break and burn methods, and double-read data from the Cooperative Aging Project (CAP) and the Washington Department of Fish and Wildlife (WDFW), as well information from a bomb radiocarbon age validation study for `r spp` off the U.S. West Coast [@haltuch_status_2009, @haltuch_california_2013], were used to generate multiple ageing error matrices, to incorporate ageing bias and imprecision into the assessment model.
 
The ageing error matrices used in the previous assessment were retained for this analysis (Tables \ref{tab:ageing-error-cap} and \ref{tab:ageing-error-wdfw}). Ageing error was explored in the last full assessment including extensive model selection. A qualitative examination of the new break and burn double reads showed no evidence that the ageing estimation had changed over time relative to the samples included in the previous analysis. Furthermore, a new TMB-based ageing error software has been developed (pers. comm. A. Punt, University of Washington), but has not yet been fully explored or documented. Therefore, revision of the ageing error matrices has been left as a research project to be completed in time for the next full assessment.
 