## Environmental and Ecosystem Data

\ref{ecosystem-considerations}
Over the past several years, progress has been made in understanding how large-scale climate forcing drives regional changes and impacts density-independent survival during `r spp` early life stages. Haltuch et al. [-@haltuch_oceanographic_2020] examined the relationship between `r spp` recruitment and oceanographic drivers based on model output from a Regional Ocean Modeling System (ROMS) model for the California Current Ecosystem (Neveu et al. 2016). The results suggested that ROMS output might be useful as the basis for an environmental index of recruitment for `r spp`, to allow for better model precision and near-term forecasting. However, the ROMS model used by Haltuch et al. [-@haltuch_oceanographic_2020] was consistent in structure and inputs for only 1980--2010. In 2011, the model was updated, and from 2011 forward, ROMS outputs exhibit distinct discontinuities with the 1980--2010 period, showing changes in scale and trend across the 2010/2011 boundary for multiple drivers used to inform the index by Haltuch et al. [-@haltuch_oceanographic_2020]. Appendix A of this report illustrates the discontinuities in ROMS products over the 2010/2011 boundary and discusses potential reasons for why the ROMS time series changed after the model was updated in 2011.

Due to discontinuity in ROMS models between periods before and after 2011, the index developed by Haltuch et al. [-@haltuch_oceanographic_2020] could not be used for this stock assessment. However, alternative oceanographic model products by Copernicus Marine Environment Monitoring Service (CMEMS) (https://marine.copernicus.eu/) and Mercator Ocean International (MOI) (https://www.mercator-ocean.eu/) were investigated to test if these modeling frameworks could be used to produce an environmental index of `r spp` recruitment. This new effort is ongoing, and has not yet been published or reviewed by the \gls{ssc} of the \gls{pfmc}. Appendix A of this report describes the most recent, preliminary efforts in developing a new environmental index of `r spp` recruitment based on CMEMS products. In this assessment, we explore the impact of the current CMEMS-based environmental index of `r spp` recruitment via sensitivity analysis.

