# Introduction
## Basic Information
`r executive[["stock"]]`

## Life History
Petrale sole spawn during the winter at several discrete deepwater sites (270-460 m) off the U.S. west coast, from November to April, with peak spawning taking place from December to February (Harry 1959; Best 1960; Gregory and Jow 1976; Castillo et al. 1993; Carison and Miller 1982; Reilly et al. 1994; Castillo 1995; Love 1996; Moser 1996a; Casillas et al. 1998).  Females spawn once each year and fecundity varies with fish size, with one large female laying as many as 1.5 million eggs (Porter, 1964). Petrale sole eggs are planktonic, ranging in size from 1.2 to 1.3 mm, and are found in deep water habitats at water temperatures of 4–10 degrees C and salinities of 25–30 ppt (Best 1960; Ketchen and Forrester, 1966; Alderdice and Forrester 1971; Gregory and Jow 1976). The duration of the egg stage can range from approximately 6 to 14 days (Alderdice and Forrester 1971; Hart 1973; Love 1996, Casillas et al. 1998). The most favorable conditions for egg incubation and larval growth are 6–7 degrees C and 27.5–29.5 ppt (Ketchen and Forrester, 1966; Alderdice and Forrester, 1971; Castillo et al., 1995). Predators of petrale sole eggs include planktonic invertebrates and pelagic fishes (Casillas et al. 1998). 

Petrale sole larvae are planktonic, ranging in size from approximately 3 to 20 mm, and are found up to 150 km offshore foraging upon copepod eggs and nauplii (Hart 1973; Moser 1996a; MBS Appl. Env. Sci 198; Casillas et al. 1998). The larval duration, including the egg stage, spans approximately 6 months with larvae settling at about 2.2 cm in length on the inner continental shelf (Pearcy 1977). Juveniles are benthic and found on sandy or sand-mud bottoms (Eschmeyer and Herald 1983; MBS Appl. Environ. Sci. 1987) and range in size from approximately 2.2 cm to the size at maturity, 50% of the population is mature at approximately 38 cm and 41 cm for males and females, respectively (Casillas et al. 1998). No specific areas have been identified as nursery grounds for juvenile petrale sole.  In the waters off British Columbia, Canada larvae are usually found in the upper 50 m far offshore, juveniles at 19–82 m and large juveniles at 25–125 m (Starr and Fargo 2004). 

Adult petrale sole achieve a maximum size of around 50 cm and 63 cm for males and females, respectively (Best 1963; Pedersen 1975). The maximum length reported for petrale sole is 70 cm (Hart 1973; Eschmeyer and Herald 1983; Love et al. 2005) while the maximum observed break and burn age is 31 years (Haltuch et al. 2013).

## Ecosystem Considerations
Petrale sole juveniles are carnivorous, foraging on annelid worms, clams, brittle star, mysids, sculpin, amphipods, and other juvenile flatfish (Ford 1965; Casillas et al. 1998; Pearsall and Fargo 2007). Predators on juvenile petrale sole include adult petrale sole as well as other larger fish (Ford 1965; Casillas et al. 1998) while adults are preyed upon by marine mammals, sharks, and larger fishes (Trumble 1995; Love 1996; Casillas et al. 1998).

One of the ambushing flatfishes, adult petrale sole have diverse diets that become more piscivorous at larger sizes (Allen et al. 2006). Adult petrale sole are found on sandy and sand-mud bottoms (Eschmeyer and Herald 1983) foraging for a variety of invertebrates including, crab, octopi, squid, euphausiids, and shrimp, as well as anchovies. hake, herring, sand lance, and other smaller rockfish and flatfish (Ford 1965; Hart 1973; Kravitz et al. 1977; Birtwell et al. 1984; Reilly et al. 1994; Love 1996; Pearsall and Fargo 2007). In Canadian waters evidence suggests that petrale sole tend to prefer herring (Pearsall and Fargo 2007). On the continental shelf petrale sole generally co-occur with English sole, rex sole, Pacific sanddab, and rock sole (Kravitz et al. 1977). 

Ecosystem factors have not been explicitly modeled in this assessment, but there are several aspects of the California current ecosystem that may impact petrale sole population dynamics and warrant further research. Castillo (1992) and Castillo et al. (1995) suggest that density-independent survival of early life stages is low and show that offshore Ekman transportation of eggs and larvae may be an important source of variation in year-class strength in the Columbia INPFC area. The effects of the Pacific Decadal Oscillation (PDO) on California current temperature and productivity (Mantua et al. 1997) may also contribute to non-stationary recruitment dynamics for petrale sole. The prevalence of a strong late 1990s year-class for many west coast groundfish species suggests that environmentally driven recruitment variation may be correlated among species with relatively diverse life history strategies. Although current research efforts along these lines are limited, a more explicit exploration of ecosystem processes may be possible in future petrale sole stock assessments.

## Historical and Current Fishery Information
Petrale sole have been caught in the flatfish fishery off the U.S. Pacific coast since the late 19th century. The fishery first developed off of California where, prior to 1876, fishing in San Francisco Bay was by hand or set lines and beach seining (Scofield 1948). By 1880 two San Francisco based trawler companies were running a total of six boats, extending the fishing grounds beyond the Golden Gate Bridge northward to Point Reyes (Scofield 1948). Steam trawlers entered the fishery during 1888 and 1889, and four steam tugs based out of San Francisco were sufficient to flood market with flatfish (Scofield 1948). By 1915 San Francisco and Santa Cruz trawlers were operating at depths of about 45–100 m with catches averaging 10,000 lbs per tow or 3,000 lbs per hour (Scofield 1948). Flatfish comprised approximately 90% of the catch with 20–25% being discarded as unmarketable (Scofield 1948). During 1915 laws were enacted that prohibited dragging in California waters and making it illegal to possess a trawl net from Santa Barbara County southward (Scofield 1948). By 1934 twenty 56–72 foot diesel engine trawlers operated out of San Francisco fishing between about 55 and 185 m (Scofield 1948).  From 1944-1947 the number of California trawlers fluctuated between 16 and 46 boats (Scofield 1948). Although the flatfish fishery in California was well developed by the 1950s and 1960s, catch statistics were not reported until 1970 (Heimann and Carlisle 1970). In this early California report petrale sole landings during 1916 to 1930 were not separated from the total flatfish landings. During 1931–68, the landings of petrale sole averaged about 700 mt annually.

The earliest trawl fishing off Oregon began during 1884-1885, and the fishery was solidly established by 1937, with the fishery increasing rapidly during WWII (Harry and Morgan, 1961). Initially trawlers stayed close to the fishing grounds adjacent to Newport and Astoria, operating at about 35–90 m between Stonewall Bank and Depoe Bay. Fishing operations gradually extended into deep water. For example, Newport-based trawlers were commonly fishing at about 185 m in 1949, at about 185–365 m by 1952, and at about 550 m by 1953. 

Alverson and Chatwin (1957) describe the history of the petrale sole fishery off of Washington and British Columbia with fishing grounds ranging from Cape Flattery to Destruction Island. Petrale catches off of Washington were small until the late 1930s with the fishery extending to about 365 m following the development of deepwater rockfish fisheries during the 1950s.   

By the 1950s the petrale sole fishery was showing signs of depletion with reports suggesting that petrale sole abundance had declined by at least 50% from 1942 to 1947 (Harry 1956). Sampson and Lee (1999) reported that three fishery regulations were implemented during 1957–67: 1) a winter closure off Oregon, Washington and British Columbia, 2) a 3,000 lb per trip limit, and 3) no more than two trips per month during 1957. With the 1977 enactment of the Magnuson Fishery Conservation and Management Act (MFCMA) the large foreign-dominated fishery that had developed since the late 1960s was replaced by the domestic fishery that continues today. Petrale sole are harvested almost exclusively by bottom trawls in the U.S. west coast groundfish fishery. Recent petrale sole catches exhibit marked seasonal variation, with substantial portions of the annual harvest taken from the spawning grounds during December and January. Evidence suggests that the winter fishery on the deepwater spawning grounds developed sporadically during the 1950s and 1960s as fishers discovered new locations (e.g., Alverson and Chatwin, 1957; Ketchen and Forrester, 1966). Both historical and current petrale sole fisheries have primarily relied upon trawl fleets. Fishery removals were divided among 4 fleets: 1) winter North trawl, 2) summer North trawl, 3) winter South trawl, and 4) summer South trawl. Landings for the North fleet are defined as fish landed in Washington and Oregon ports. Landings for the South fleet are defined as fish landed in California ports.

## Summary of Management History and Performance
Replace text.

## Foreign Fisheries
The Canadian fishery developed rapidly during the late 1940s to mid-1950s following the discovery of petrale sole spawning aggregations off the west coast of Vancouver Island (Anon. 2001). Annual landings of petrale sole in British Columbia peaked at 4,800 mt in 1948 but declined significantly after the mid-1960s (Anon. 2001). By the 1970s, analysis conducted by Pederson (1975) suggested that petrale abundance was low and abundance remained low into the 1990s. In the early 1990s vessel trip quotas were established to try to halt the decline in petrale sole abundance (Anon. 2001). Winter quarter landings of petrale sole were limited to 44,000 lb per trip during 1985–91; to 10,000 lb per trip during 1991–95; and to 2,000 lb per trip in 1996. Biological data collected during 1980-1996 showed a prolonged decline in the proportion of young fish entering the population (Anon. 2001). Therefore, no directed fishing for petrale sole has been permitted in Canada since 1996 due to a continuing decline in long term abundance (Fargo, 1997, Anon. 2001). Current landings of petrale sole in Canada are very low due to the effect of the non-directed fishery. As of 2005 petrale sole off of British Columbia were treated as three “stocks” and were still considered to be at low levels. The recent assessments for the Canadian stocks have been based on catch histories and limited biological data. 

The most recent assessment of petrale sole in British Columbia uses a single area combined sex delay-difference stock assessment model with knife edge recruitment (at 6 or 7 years old) and tuned to fishery CPUE, mean fish weight of the commercial landings, and a number of fishery independent surveys beginning in the early 1980s (P. Starr, pers. comm.). Stock predictions are based on average recruitment (P. Starr, pers. comm.) This assessment suggests that the stock is currently above the target reference point and that there is some evidence for above average recruitment (about 10% above average) since about 1996 (P. Starr, pers. comm.). Petrale sole in Canadian waters appear to have similar life history characteristics (Starr and Fargo 2004). The Canadian assessment has not been updated between the U.S. petrale sole 2011 and 2013 assessments. 

In Alaska petrale sole are not targeted in the Bering Sea/Aleutian Island fisheries and are managed as a minor species in the “Other Flatfish” stock complex.
